### ISSUE TITLE
Line Break 

### ISSUE THREAD

**Issue by gjmm07** [Markus-de-Koster/LaTeX-beamer-TH-Koeln#1]
I am having issues with long frame titles. There is no such thing as a line break. Any recommendations how to solve it? Many thanks!

**Comment by Markus-de-Koster** [comment]
Thank you for the feedback!
You were right, It was impossible to include line breaks in any macro (such as frame title, title, author etc.). 

Fixed in [#8fe1326.](https://github.com/Markus-de-Koster/LaTeX-beamer-TH-Koeln/commit/8fe1326da7b18b271382d915d79384e8a35c9698) Example usage:
`\frametitle{Two line \\ title} `

Note though, that this will collide with other elements such as subtitles. Adjusting other elements' positions dynamically is too much effort (if even possible?)

**Comment by gjmm07** [comment]
That does the job. Thanks
